# Site settings
title: "Jason Weitzel"
description: "Cyber Architect"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jason Weitzel"
resume_title:                   "Cyber Architect"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jasonweitzel@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       ""
resume_contact_address:         ""

resume_header_contact_info:     ""
display_header_contact_info:    ""

resume_header_intro: |
  Dedicated Cyber Security Architect who is proficient in deploying, maintaining, 
  and securing a complex enterprise-level system of systems. Specialized in 
  implementing DevSecOps best practices to create hardened operating systems and 
  applications.

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
# resume_section_recognition:     true
# resume_section_links:           true
# resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:             "https://github.com/brokenkazoo"
  # resume_twitter_url:          ""
  # resume_dribbble_url:         ""
  resume_facebook_url:           "https://www.facebook.com/jcweitzel"
  #resume_linkedin_url:          ""
  # resume_instagram_url:        ""
  resume_website_url:            "https://brokenkazoo.github.io/resume/"
  # resume_medium_url:           ""
resume_print_social_links:       true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
